name: Z Vernon
title: Z Vernon | A Resume
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Experience
    url: /Experience
  - title: Skills
    url: /Skills
  - title: Projects
    url: /Projects
  - title: Contact
    url: /contact
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
